from setuptools import setup, find_packages

setup(
    name="drf-keycloak-simple",
    version="0.1.0",
    packages=find_packages(),
    install_requires=[
        "django>=3.0",
        "djangorestframework>=3.12.0",
        "python-keycloak>=2.5.0",
        "PyJWT>=2.0.0",
        "requests>=2.25.0",
        "requests-oauthlib>=1.3.0",
    ],
    author="Charalambos Paschalides",
    author_email="already.late@gmail.com",
    description="A Django REST framework authentication package for Keycloak",
    long_description=open("README.md").read(),
    long_description_content_type="text/markdown",
    url="https://github.com/stargazer/drf-keycloak-simple",
    classifiers=[
        "Development Status :: 4 - Beta",
        "Environment :: Web Environment",
        "Framework :: Django",
        "Framework :: Django :: 3.0",
        "Intended Audience :: Developers",
        "License :: OSI Approved :: MIT License",
        "Operating System :: OS Independent",
        "Programming Language :: Python",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.7",
        "Programming Language :: Python :: 3.8",
        "Programming Language :: Python :: 3.9",
        "Topic :: Internet :: WWW/HTTP",
        "Topic :: Security :: Authentication",
    ],
    python_requires=">=3.7",
)
